#!/bin/bash
cd ..
mv dist/* dist_old/
printf "Enter version #: "
read vnum
printf "Enter previous version #: "
read pvnum
repstr="s/version='$pvnum'/version='$vnum'/"
sed -i $repstr setup.py
python3 setup.py sdist
python3 -m twine upload dist/*
